/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : Time,
  'blobId' : ExternalBlob,
  'mediaType' : IDL.Text,
});
export const StaffMember = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'blobId' : IDL.Opt(ExternalBlob),
});
export const SubjectResult = IDL.Record({
  'marks' : IDL.Nat,
  'subject' : IDL.Text,
  'grade' : IDL.Text,
});
export const StudentResult = IDL.Record({
  'id' : IDL.Nat,
  'studentName' : IDL.Text,
  'subjects' : IDL.Vec(SubjectResult),
  'academicYear' : IDL.Text,
  'rollNumber' : IDL.Text,
  'blobId' : IDL.Opt(ExternalBlob),
  'studentClass' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NewsEvent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isPublished' : IDL.Bool,
  'body' : IDL.Text,
  'date' : Time,
  'blobId' : IDL.Opt(ExternalBlob),
});
export const Notice = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isPublished' : IDL.Bool,
  'body' : IDL.Text,
  'date' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const PrincipalMessage = IDL.Record({
  'message' : IDL.Text,
  'blobId' : IDL.Opt(ExternalBlob),
  'principalName' : IDL.Text,
});
export const SchoolInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'mapEmbedUrl' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryItem' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Text],
      [GalleryItem],
      [],
    ),
  'addStaffMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [StaffMember],
      [],
    ),
  'addStudentResult' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(SubjectResult),
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [StudentResult],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNewsEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [NewsEvent],
      [],
    ),
  'createNotice' : IDL.Func([IDL.Text, IDL.Text], [Notice], []),
  'deleteContactMessage' : IDL.Func([IDL.Nat], [], []),
  'deleteGalleryItem' : IDL.Func([IDL.Nat], [], []),
  'deleteNewsEvent' : IDL.Func([IDL.Nat], [], []),
  'deleteNotice' : IDL.Func([IDL.Nat], [], []),
  'deleteStaffMember' : IDL.Func([IDL.Nat], [], []),
  'deleteStudentResult' : IDL.Func([IDL.Nat], [], []),
  'getAllResults' : IDL.Func([], [IDL.Vec(StudentResult)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getNewsEvents' : IDL.Func([], [IDL.Vec(NewsEvent)], ['query']),
  'getNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getPrincipalMessage' : IDL.Func([], [IDL.Opt(PrincipalMessage)], ['query']),
  'getPublishedNewsEvents' : IDL.Func([], [IDL.Vec(NewsEvent)], ['query']),
  'getPublishedNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getSchoolInfo' : IDL.Func([], [IDL.Opt(SchoolInfo)], ['query']),
  'getStaffMembers' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishNewsEvent' : IDL.Func([IDL.Nat], [], []),
  'publishNotice' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchResultsByRollNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudentResult)],
      ['query'],
    ),
  'setPrincipalMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'setSchoolInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateNewsEvent' : IDL.Func([NewsEvent], [], []),
  'updateNotice' : IDL.Func([Notice], [], []),
  'updateStaffMember' : IDL.Func([StaffMember], [], []),
  'updateStudentResult' : IDL.Func([StudentResult], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : Time,
    'blobId' : ExternalBlob,
    'mediaType' : IDL.Text,
  });
  const StaffMember = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'blobId' : IDL.Opt(ExternalBlob),
  });
  const SubjectResult = IDL.Record({
    'marks' : IDL.Nat,
    'subject' : IDL.Text,
    'grade' : IDL.Text,
  });
  const StudentResult = IDL.Record({
    'id' : IDL.Nat,
    'studentName' : IDL.Text,
    'subjects' : IDL.Vec(SubjectResult),
    'academicYear' : IDL.Text,
    'rollNumber' : IDL.Text,
    'blobId' : IDL.Opt(ExternalBlob),
    'studentClass' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NewsEvent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isPublished' : IDL.Bool,
    'body' : IDL.Text,
    'date' : Time,
    'blobId' : IDL.Opt(ExternalBlob),
  });
  const Notice = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isPublished' : IDL.Bool,
    'body' : IDL.Text,
    'date' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PrincipalMessage = IDL.Record({
    'message' : IDL.Text,
    'blobId' : IDL.Opt(ExternalBlob),
    'principalName' : IDL.Text,
  });
  const SchoolInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'mapEmbedUrl' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryItem' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Text],
        [GalleryItem],
        [],
      ),
    'addStaffMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [StaffMember],
        [],
      ),
    'addStudentResult' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(SubjectResult),
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [StudentResult],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNewsEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [NewsEvent],
        [],
      ),
    'createNotice' : IDL.Func([IDL.Text, IDL.Text], [Notice], []),
    'deleteContactMessage' : IDL.Func([IDL.Nat], [], []),
    'deleteGalleryItem' : IDL.Func([IDL.Nat], [], []),
    'deleteNewsEvent' : IDL.Func([IDL.Nat], [], []),
    'deleteNotice' : IDL.Func([IDL.Nat], [], []),
    'deleteStaffMember' : IDL.Func([IDL.Nat], [], []),
    'deleteStudentResult' : IDL.Func([IDL.Nat], [], []),
    'getAllResults' : IDL.Func([], [IDL.Vec(StudentResult)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getNewsEvents' : IDL.Func([], [IDL.Vec(NewsEvent)], ['query']),
    'getNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getPrincipalMessage' : IDL.Func(
        [],
        [IDL.Opt(PrincipalMessage)],
        ['query'],
      ),
    'getPublishedNewsEvents' : IDL.Func([], [IDL.Vec(NewsEvent)], ['query']),
    'getPublishedNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getSchoolInfo' : IDL.Func([], [IDL.Opt(SchoolInfo)], ['query']),
    'getStaffMembers' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishNewsEvent' : IDL.Func([IDL.Nat], [], []),
    'publishNotice' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchResultsByRollNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudentResult)],
        ['query'],
      ),
    'setPrincipalMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'setSchoolInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateNewsEvent' : IDL.Func([NewsEvent], [], []),
    'updateNotice' : IDL.Func([Notice], [], []),
    'updateStaffMember' : IDL.Func([StaffMember], [], []),
    'updateStudentResult' : IDL.Func([StudentResult], [], []),
  });
};

export const init = ({ IDL }) => { return []; };