/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'id' : bigint,
  'date' : Time,
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'id' : bigint,
  'title' : string,
  'date' : Time,
  'blobId' : ExternalBlob,
  'mediaType' : string,
}
export interface NewsEvent {
  'id' : bigint,
  'title' : string,
  'isPublished' : boolean,
  'body' : string,
  'date' : Time,
  'blobId' : [] | [ExternalBlob],
}
export interface Notice {
  'id' : bigint,
  'title' : string,
  'isPublished' : boolean,
  'body' : string,
  'date' : Time,
}
export interface PrincipalMessage {
  'message' : string,
  'blobId' : [] | [ExternalBlob],
  'principalName' : string,
}
export interface SchoolInfo {
  'name' : string,
  'email' : string,
  'address' : string,
  'mapEmbedUrl' : string,
  'phone' : string,
}
export interface StaffMember {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'designation' : string,
  'blobId' : [] | [ExternalBlob],
}
export interface StudentResult {
  'id' : bigint,
  'studentName' : string,
  'subjects' : Array<SubjectResult>,
  'academicYear' : string,
  'rollNumber' : string,
  'blobId' : [] | [ExternalBlob],
  'studentClass' : string,
}
export interface SubjectResult {
  'marks' : bigint,
  'subject' : string,
  'grade' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / ******** Gallery *********
   */
  'addGalleryItem' : ActorMethod<[string, ExternalBlob, string], GalleryItem>,
  /**
   * / ******** Staff *********
   */
  'addStaffMember' : ActorMethod<
    [string, string, string, [] | [ExternalBlob]],
    StaffMember
  >,
  /**
   * / ******** Student Results *********
   */
  'addStudentResult' : ActorMethod<
    [string, string, string, Array<SubjectResult>, string, [] | [ExternalBlob]],
    StudentResult
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / ******** News/Events *********
   */
  'createNewsEvent' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    NewsEvent
  >,
  /**
   * / ******** Notices *********
   */
  'createNotice' : ActorMethod<[string, string], Notice>,
  'deleteContactMessage' : ActorMethod<[bigint], undefined>,
  'deleteGalleryItem' : ActorMethod<[bigint], undefined>,
  'deleteNewsEvent' : ActorMethod<[bigint], undefined>,
  'deleteNotice' : ActorMethod<[bigint], undefined>,
  'deleteStaffMember' : ActorMethod<[bigint], undefined>,
  'deleteStudentResult' : ActorMethod<[bigint], undefined>,
  'getAllResults' : ActorMethod<[], Array<StudentResult>>,
  /**
   * / ******** User Profile Functions *********
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getNewsEvents' : ActorMethod<[], Array<NewsEvent>>,
  'getNotices' : ActorMethod<[], Array<Notice>>,
  'getPrincipalMessage' : ActorMethod<[], [] | [PrincipalMessage]>,
  'getPublishedNewsEvents' : ActorMethod<[], Array<NewsEvent>>,
  'getPublishedNotices' : ActorMethod<[], Array<Notice>>,
  'getSchoolInfo' : ActorMethod<[], [] | [SchoolInfo]>,
  'getStaffMembers' : ActorMethod<[], Array<StaffMember>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishNewsEvent' : ActorMethod<[bigint], undefined>,
  'publishNotice' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchResultsByRollNumber' : ActorMethod<[string], Array<StudentResult>>,
  /**
   * / ******** Principal Message *********
   */
  'setPrincipalMessage' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    undefined
  >,
  /**
   * / ******** School Info *********
   */
  'setSchoolInfo' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  /**
   * / ******** Contact Messages *********
   */
  'submitContactMessage' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateNewsEvent' : ActorMethod<[NewsEvent], undefined>,
  'updateNotice' : ActorMethod<[Notice], undefined>,
  'updateStaffMember' : ActorMethod<[StaffMember], undefined>,
  'updateStudentResult' : ActorMethod<[StudentResult], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];