/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface PrincipalMessage {
    message: string;
    blobId?: ExternalBlob;
    principalName: string;
}
export interface SubjectResult {
    marks: bigint;
    subject: string;
    grade: string;
}
export type Time = bigint;
export interface NewsEvent {
    id: bigint;
    title: string;
    isPublished: boolean;
    body: string;
    date: Time;
    blobId?: ExternalBlob;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface StaffMember {
    id: bigint;
    bio: string;
    name: string;
    designation: string;
    blobId?: ExternalBlob;
}
export interface ContactMessage {
    id: bigint;
    date: Time;
    name: string;
    email: string;
    message: string;
    phone: string;
}
export interface SchoolInfo {
    name: string;
    email: string;
    address: string;
    mapEmbedUrl: string;
    phone: string;
}
export interface Notice {
    id: bigint;
    title: string;
    isPublished: boolean;
    body: string;
    date: Time;
}
export interface GalleryItem {
    id: bigint;
    title: string;
    date: Time;
    blobId: ExternalBlob;
    mediaType: string;
}
export interface StudentResult {
    id: bigint;
    studentName: string;
    subjects: Array<SubjectResult>;
    academicYear: string;
    rollNumber: string;
    blobId?: ExternalBlob;
    studentClass: string;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / ******** Gallery *********
     */
    addGalleryItem(title: string, blobId: ExternalBlob, mediaType: string): Promise<GalleryItem>;
    /**
     * / ******** Staff *********
     */
    addStaffMember(name: string, designation: string, bio: string, blobId: ExternalBlob | null): Promise<StaffMember>;
    /**
     * / ******** Student Results *********
     */
    addStudentResult(rollNumber: string, studentName: string, studentClass: string, subjects: Array<SubjectResult>, academicYear: string, blobId: ExternalBlob | null): Promise<StudentResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / ******** News/Events *********
     */
    createNewsEvent(title: string, body: string, blobId: ExternalBlob | null): Promise<NewsEvent>;
    /**
     * / ******** Notices *********
     */
    createNotice(title: string, body: string): Promise<Notice>;
    deleteContactMessage(id: bigint): Promise<void>;
    deleteGalleryItem(id: bigint): Promise<void>;
    deleteNewsEvent(id: bigint): Promise<void>;
    deleteNotice(id: bigint): Promise<void>;
    deleteStaffMember(id: bigint): Promise<void>;
    deleteStudentResult(id: bigint): Promise<void>;
    getAllResults(): Promise<Array<StudentResult>>;
    /**
     * / ******** User Profile Functions *********
     */
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContactMessages(): Promise<Array<ContactMessage>>;
    getGalleryItems(): Promise<Array<GalleryItem>>;
    getNewsEvents(): Promise<Array<NewsEvent>>;
    getNotices(): Promise<Array<Notice>>;
    getPrincipalMessage(): Promise<PrincipalMessage | null>;
    getPublishedNewsEvents(): Promise<Array<NewsEvent>>;
    getPublishedNotices(): Promise<Array<Notice>>;
    getSchoolInfo(): Promise<SchoolInfo | null>;
    getStaffMembers(): Promise<Array<StaffMember>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    publishNewsEvent(id: bigint): Promise<void>;
    publishNotice(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchResultsByRollNumber(rollNumber: string): Promise<Array<StudentResult>>;
    /**
     * / ******** Principal Message *********
     */
    setPrincipalMessage(message: string, principalName: string, blobId: ExternalBlob | null): Promise<void>;
    /**
     * / ******** School Info *********
     */
    setSchoolInfo(name: string, address: string, phone: string, email: string, mapEmbedUrl: string): Promise<void>;
    /**
     * / ******** Contact Messages *********
     */
    submitContactMessage(name: string, email: string, phone: string, message: string): Promise<void>;
    updateNewsEvent(newsEvent: NewsEvent): Promise<void>;
    updateNotice(notice: Notice): Promise<void>;
    updateStaffMember(staff: StaffMember): Promise<void>;
    updateStudentResult(result: StudentResult): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, GalleryItem as _GalleryItem, NewsEvent as _NewsEvent, PrincipalMessage as _PrincipalMessage, SchoolInfo as _SchoolInfo, StaffMember as _StaffMember, StudentResult as _StudentResult, SubjectResult as _SubjectResult, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addGalleryItem(arg0: string, arg1: ExternalBlob, arg2: string): Promise<GalleryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryItem(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_GalleryItem_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryItem(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_GalleryItem_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async addStaffMember(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob | null): Promise<StaffMember> {
        if (this.processError) {
            try {
                const result = await this.actor.addStaffMember(arg0, arg1, arg2, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3));
                return from_candid_StaffMember_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStaffMember(arg0, arg1, arg2, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3));
            return from_candid_StaffMember_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async addStudentResult(arg0: string, arg1: string, arg2: string, arg3: Array<SubjectResult>, arg4: string, arg5: ExternalBlob | null): Promise<StudentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudentResult(arg0, arg1, arg2, arg3, arg4, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg5));
                return from_candid_StudentResult_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudentResult(arg0, arg1, arg2, arg3, arg4, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg5));
            return from_candid_StudentResult_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createNewsEvent(arg0: string, arg1: string, arg2: ExternalBlob | null): Promise<NewsEvent> {
        if (this.processError) {
            try {
                const result = await this.actor.createNewsEvent(arg0, arg1, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2));
                return from_candid_NewsEvent_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNewsEvent(arg0, arg1, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2));
            return from_candid_NewsEvent_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNotice(arg0: string, arg1: string): Promise<Notice> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotice(arg0, arg1);
            return result;
        }
    }
    async deleteContactMessage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContactMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContactMessage(arg0);
            return result;
        }
    }
    async deleteGalleryItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryItem(arg0);
            return result;
        }
    }
    async deleteNewsEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNewsEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNewsEvent(arg0);
            return result;
        }
    }
    async deleteNotice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotice(arg0);
            return result;
        }
    }
    async deleteStaffMember(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStaffMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStaffMember(arg0);
            return result;
        }
    }
    async deleteStudentResult(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudentResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudentResult(arg0);
            return result;
        }
    }
    async getAllResults(): Promise<Array<StudentResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResults();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResults();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactMessages(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactMessages();
            return result;
        }
    }
    async getGalleryItems(): Promise<Array<GalleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryItems();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryItems();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsEvents(): Promise<Array<NewsEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsEvents();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsEvents();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotices(): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotices();
            return result;
        }
    }
    async getPrincipalMessage(): Promise<PrincipalMessage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrincipalMessage();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrincipalMessage();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedNewsEvents(): Promise<Array<NewsEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedNewsEvents();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedNewsEvents();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedNotices(): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedNotices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedNotices();
            return result;
        }
    }
    async getSchoolInfo(): Promise<SchoolInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchoolInfo();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSchoolInfo();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaffMembers(): Promise<Array<StaffMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffMembers();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffMembers();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async publishNewsEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishNewsEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishNewsEvent(arg0);
            return result;
        }
    }
    async publishNotice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishNotice(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchResultsByRollNumber(arg0: string): Promise<Array<StudentResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchResultsByRollNumber(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchResultsByRollNumber(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async setPrincipalMessage(arg0: string, arg1: string, arg2: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPrincipalMessage(arg0, arg1, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPrincipalMessage(arg0, arg1, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async setSchoolInfo(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSchoolInfo(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSchoolInfo(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitContactMessage(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactMessage(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactMessage(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateNewsEvent(arg0: NewsEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNewsEvent(await to_candid_NewsEvent_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNewsEvent(await to_candid_NewsEvent_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateNotice(arg0: Notice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNotice(arg0);
            return result;
        }
    }
    async updateStaffMember(arg0: StaffMember): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaffMember(await to_candid_StaffMember_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaffMember(await to_candid_StaffMember_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateStudentResult(arg0: StudentResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudentResult(await to_candid_StudentResult_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudentResult(await to_candid_StudentResult_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GalleryItem_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryItem): Promise<GalleryItem> {
    return await from_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_NewsEvent_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsEvent): Promise<NewsEvent> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_PrincipalMessage_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrincipalMessage): Promise<PrincipalMessage> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_StaffMember_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffMember): Promise<StaffMember> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_StudentResult_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentResult): Promise<StudentResult> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PrincipalMessage]): Promise<PrincipalMessage | null> {
    return value.length === 0 ? null : await from_candid_PrincipalMessage_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SchoolInfo]): SchoolInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    date: _Time;
    blobId: _ExternalBlob;
    mediaType: string;
}): Promise<{
    id: bigint;
    title: string;
    date: Time;
    blobId: ExternalBlob;
    mediaType: string;
}> {
    return {
        id: value.id,
        title: value.title,
        date: value.date,
        blobId: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.blobId),
        mediaType: value.mediaType
    };
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bio: string;
    name: string;
    designation: string;
    blobId: [] | [_ExternalBlob];
}): Promise<{
    id: bigint;
    bio: string;
    name: string;
    designation: string;
    blobId?: ExternalBlob;
}> {
    return {
        id: value.id,
        bio: value.bio,
        name: value.name,
        designation: value.designation,
        blobId: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.blobId))
    };
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    studentName: string;
    subjects: Array<_SubjectResult>;
    academicYear: string;
    rollNumber: string;
    blobId: [] | [_ExternalBlob];
    studentClass: string;
}): Promise<{
    id: bigint;
    studentName: string;
    subjects: Array<SubjectResult>;
    academicYear: string;
    rollNumber: string;
    blobId?: ExternalBlob;
    studentClass: string;
}> {
    return {
        id: value.id,
        studentName: value.studentName,
        subjects: value.subjects,
        academicYear: value.academicYear,
        rollNumber: value.rollNumber,
        blobId: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.blobId)),
        studentClass: value.studentClass
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    isPublished: boolean;
    body: string;
    date: _Time;
    blobId: [] | [_ExternalBlob];
}): Promise<{
    id: bigint;
    title: string;
    isPublished: boolean;
    body: string;
    date: Time;
    blobId?: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        isPublished: value.isPublished,
        body: value.body,
        date: value.date,
        blobId: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.blobId))
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    message: string;
    blobId: [] | [_ExternalBlob];
    principalName: string;
}): Promise<{
    message: string;
    blobId?: ExternalBlob;
    principalName: string;
}> {
    return {
        message: value.message,
        blobId: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.blobId)),
        principalName: value.principalName
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentResult>): Promise<Array<StudentResult>> {
    return await Promise.all(value.map(async (x)=>await from_candid_StudentResult_n16(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryItem>): Promise<Array<GalleryItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryItem_n9(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NewsEvent>): Promise<Array<NewsEvent>> {
    return await Promise.all(value.map(async (x)=>await from_candid_NewsEvent_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StaffMember>): Promise<Array<StaffMember>> {
    return await Promise.all(value.map(async (x)=>await from_candid_StaffMember_n13(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_NewsEvent_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsEvent): Promise<_NewsEvent> {
    return await to_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function to_candid_StaffMember_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffMember): Promise<_StaffMember> {
    return await to_candid_record_n36(_uploadFile, _downloadFile, value);
}
async function to_candid_StudentResult_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentResult): Promise<_StudentResult> {
    return await to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    isPublished: boolean;
    body: string;
    date: Time;
    blobId?: ExternalBlob;
}): Promise<{
    id: bigint;
    title: string;
    isPublished: boolean;
    body: string;
    date: _Time;
    blobId: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        title: value.title,
        isPublished: value.isPublished,
        body: value.body,
        date: value.date,
        blobId: value.blobId ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.blobId)) : candid_none()
    };
}
async function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    bio: string;
    name: string;
    designation: string;
    blobId?: ExternalBlob;
}): Promise<{
    id: bigint;
    bio: string;
    name: string;
    designation: string;
    blobId: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        bio: value.bio,
        name: value.name,
        designation: value.designation,
        blobId: value.blobId ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.blobId)) : candid_none()
    };
}
async function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    studentName: string;
    subjects: Array<SubjectResult>;
    academicYear: string;
    rollNumber: string;
    blobId?: ExternalBlob;
    studentClass: string;
}): Promise<{
    id: bigint;
    studentName: string;
    subjects: Array<_SubjectResult>;
    academicYear: string;
    rollNumber: string;
    blobId: [] | [_ExternalBlob];
    studentClass: string;
}> {
    return {
        id: value.id,
        studentName: value.studentName,
        subjects: value.subjects,
        academicYear: value.academicYear,
        rollNumber: value.rollNumber,
        blobId: value.blobId ? candid_some(await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.blobId)) : candid_none(),
        studentClass: value.studentClass
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
